import { prisma } from './config/prisma.js';
import { Prisma } from '@prisma/client';

const seeDB = async () => {
  try {
    await prisma.product.deleteMany({});
    console.log('Cleared existing products');

    const products: Prisma.ProductCreateManyInput[] = [
      {
        name: 'Butter Croissant 100g',
        description: 'Flaky and buttery',
        price: 4.5,
        originalPrice: 5.0,
        image: '/images/butter_croissant_image.png',
        category: 'bakery',
        unit: '100g',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Organic Quinoa 500g',
        description: 'High protein, Gluten-free',
        price: 4.0,
        originalPrice: 4.5,
        image: '/images/organic_vegetable_image.png',
        category: 'pantry-staples',
        unit: '500g',
        stock: 100,
        isOrganic: true,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Brown Bread 400g',
        description: 'Soft and healthy, Ideal for breakfast',
        price: 3.5,
        originalPrice: 4.0,
        image: '/images/brown_bread_image.png',
        category: 'bakery',
        unit: '400g',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Barley 1kg',
        description: 'Rich in fiber, Helps digestion',
        price: 1.4,
        originalPrice: 1.5,
        image: '/images/barley_image.png',
        category: 'pantry-staples',
        unit: '1kg',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Knorr Cup Soup 70g',
        description: 'Convenient and tasty',
        price: 3.0,
        originalPrice: 3.5,
        image: '/images/knorr_soup_image.png',
        category: 'pantry-staples',
        unit: '70g',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Maggi Noodles 280g',
        description: 'Instant and easy to cook',
        price: 5.0,
        originalPrice: 5.5,
        image: '/images/maggi_image.png',
        category: 'pantry-staples',
        unit: '280g',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Sprite 1.5L',
        description: 'Chilled and refreshing, Perfect for celebrations',
        price: 6.0,
        originalPrice: 7.5,
        image: '/images/sprite_image_1.png',
        category: 'beverages',
        unit: '1.5L',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Carrot 500g',
        description:
          'Sweet and crunchy, Good for eyesight, Ideal for juices and salads',
        price: 4.49,
        originalPrice: 5.59,
        image: '/images/carrot_image.png',
        category: 'fruits-vegetables',
        unit: '500g',
        stock: 100,
        isOrganic: true,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Coca-Cola 1.5L',
        description: 'Perfect for parties and gatherings, Best served chilled',
        price: 7.5,
        originalPrice: 8.0,
        image: '/images/coca_cola_image.png',
        category: 'beverages',
        unit: '1.5L',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Brown Rice 1kg',
        description: 'Whole grain and nutritious',
        price: 8.0,
        originalPrice: 10.0,
        image: '/images/brown_rice_image.png',
        category: 'pantry-staples',
        unit: '1kg',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Eggs 12 pcs',
        description:
          'Farm fresh, Rich in protein, Ideal for breakfast and baking',
        price: 8.5,
        originalPrice: 9.0,
        image: '/images/eggs_image.png',
        category: 'dairy-eggs',
        unit: '12pcs',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Banana 1 kg',
        description:
          'Sweet and ripe, High in potassium, Great for smoothies and snacking',
        price: 4.5,
        originalPrice: 5.0,
        image: '/images/banana_image_1.png',
        category: 'fruits-vegetables',
        unit: '1kg',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Basmati Rice 5kg',
        description: 'Long grain and aromatic, Perfect for biryani',
        price: 5.2,
        originalPrice: 5.5,
        image: '/images/basmati_rice_image.png',
        category: 'pantry-staples',
        unit: '5kg',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Onion 500g',
        description: 'Fresh and pungent, Perfect for cooking, A kitchen staple',
        price: 4.5,
        originalPrice: 5.0,
        image: '/images/onion_image_1.png',
        category: 'fruits-vegetables',
        unit: '500g',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: '7 Up 1.5L',
        description: 'Refreshing lemon-lime flavor',
        price: 7.0,
        originalPrice: 7.6,
        image: '/images/seven_up_image_1.png',
        category: 'beverages',
        unit: '1.5L',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Spinach 500g',
        description:
          'Rich in iron, High in vitamins, Perfect for soups and salads',
        price: 1.5,
        originalPrice: 1.8,
        image: '/images/spinach_image_1.png',
        category: 'fruits-vegetables',
        unit: '500g',
        stock: 100,
        isOrganic: true,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Orange 1 kg',
        description:
          'Juicy2 and sweet, Rich in Vitamin C, Perfect for juices and salads',
        price: 7.5,
        originalPrice: 8.0,
        image: '/images/orange_image.png',
        category: 'fruits-vegetables',
        unit: '1kg',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Wheat Flour 5kg',
        description: 'Soft and fluffy rotis, Rich in nutrients',
        price: 2.3,
        originalPrice: 2.5,
        image: '/images/wheat_flour_image.png',
        category: 'pantry-staples',
        unit: '5kg',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Grapes 500g',
        description:
          'Fresh and juicy, Rich in antioxidants, Perfect for snacking and fruit salads',
        price: 6.5,
        originalPrice: 7.0,
        image: '/images/grapes_image_1.png',
        category: 'fruits-vegetables',
        unit: '500g',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Fanta 1.5L',
        description: 'Sweet and fizzy',
        price: 6.5,
        originalPrice: 7.0,
        image: '/images/fanta_image_1.png',
        category: 'beverages',
        unit: '1.5L',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Paneer 200g',
        description:
          'Soft and fresh, Rich in protein, Ideal for curries and snacks',
        price: 8.5,
        originalPrice: 9.0,
        image: '/images/paneer_image.png',
        category: 'dairy-eggs',
        unit: '200g',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Mango 1 kg',
        description:
          'Sweet and flavorful, Perfect for smoothies and desserts, Rich in Vitamin A',
        price: 1.4,
        originalPrice: 1.5,
        image: '/images/mango_image_1.png',
        category: 'fruits-vegetables',
        unit: '1kg',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Tomato 1 kg',
        description:
          'Juicy and ripe, Rich in Vitamin C, Perfect for salads and sauces, Farm fresh quality',
        price: 2.8,
        originalPrice: 3.0,
        image: '/images/tomato_image.png',
        category: 'fruits-vegetables',
        unit: '1kg',
        stock: 100,
        isOrganic: true,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Potato 500g',
        description:
          'Fresh and organic, Rich in carbohydrates, Ideal for curries and fries',
        price: 3.5,
        originalPrice: 4.0,
        image: '/images/potato_image_1.png',
        category: 'fruits-vegetables',
        unit: '500g',
        stock: 100,
        isOrganic: true,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Cheese 200g',
        description:
          'Creamy and delicious, Perfect for pizzas and sandwiches, Rich in calcium',
        price: 1.3,
        originalPrice: 1.4,
        image: '/images/cheese_image.png',
        category: 'dairy-eggs',
        unit: '200g',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Amul Milk 1L',
        description: 'Fresh milk, Rich in calcium',
        price: 5.5,
        originalPrice: 6.0,
        image: '/images/amul_milk_image.png',
        category: 'dairy-eggs',
        unit: '1L',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Apple 1 kg',
        description: 'Boosts immunity, Rich in fiber',
        price: 9.0,
        originalPrice: 10.0,
        image: '/images/apple_image.png',
        category: 'fruits-vegetables',
        unit: '1kg',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
    ];

    await prisma.product.createMany({ data: products });
    console.log(`Created ${products.length} products`);

    console.log('Seed completed successfully');
    process.exit(0);
  } catch (error) {
    console.error('Seed error:', error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
};

seeDB();
